src/rubintv/templates/table.html
OK, I think I've fixed those links.  Please check that I've done it correctly.  I think if I have them pointing as follows: 
window.open('/rubintv/im_current','_blank')
that it will find the right link.  That's the way the buttons on the right side are, and they work.
=> Fixing links of top four buttons

.github/workflows/ci.yaml, requirements/dev.in, requirements/dev.txt, requirements/main.in, requirements/main.txt, scripts/docker-tag.sh, src/rubintv/__init__.py
Reflect changes to the templates by updating the GitHub CI
configuration, the Docker build configuration, and the dependency
declarations.  This will allow CI runs on pull requests, but there
should otherwise not be any significant functionality changes.
=> [DM-31621] Update CI, Docker, and dependencies

src/rubintv/app.py, src/rubintv/handlers/external/endpoints.py, src/rubintv/models.py, src/rubintv/static/js/modules/table-control.js, src/rubintv/static/js/refresh-daytable.js, src/rubintv/templates/cameras/allsky-historical.jinja, src/rubintv/templates/cameras/allsky-image.jinja, src/rubintv/templates/cameras/allsky-monitor.jinja, src/rubintv/templates/cameras/camera.jinja
Adds Historical Data docstrings
Adds Google authentication for bucket access
Changes metadata handling to use proper names
Fixes a bug that prevented per day channels from refreshing
=> DM-36727: Adds Historical Data docstrings, Google authentication and changes metadata attribute name handling & fixes per day channels not refreshing

.github/workflows/ci.yaml, .gitignore, python/lsst/ts/rubintv/handlers/ddv/websocket_handler.py, python/lsst/ts/rubintv/handlers/ddv_websocket_handler.py, python/lsst/ts/rubintv/main.py, start-daemon.sh
Flutter installation via GHA CI.
Flutter run against project via start daemon.
Flutter app mounted at rubintv/ddv/app.
Websockets between Flutter app and worker pods handled in FastAPI.
=> DM-44256: Add DDV Flutter app to RubinTV

python/lsst/ts/rubintv/background/historicaldata.py, python/lsst/ts/rubintv/handlers/pages.py, python/lsst/ts/rubintv/models/models.py
Also fixes view for no current event.
=> DM-44621: Fix current event could fetch old event

.github/workflows/ci.yaml, python/lsst/ts/rubintv/background/background_helpers.py, python/lsst/ts/rubintv/background/currentpoller.py, python/lsst/ts/rubintv/background/historicaldata.py, python/lsst/ts/rubintv/handlers/api.py, python/lsst/ts/rubintv/handlers/ddv_routes_handler.py, python/lsst/ts/rubintv/handlers/ddv_websocket_handler.py, python/lsst/ts/rubintv/handlers/heartbeat_server.py, python/lsst/ts/rubintv/handlers/pages_helpers.py, python/lsst/ts/rubintv/handlers/websocket.py, python/lsst/ts/rubintv/main.py, python/lsst/ts/rubintv/models/models.py, python/lsst/ts/rubintv/models/models_helpers.py, python/lsst/ts/rubintv/models/models_init.py, python/lsst/ts/rubintv/s3client.py, python/lsst/ts/rubintv/templates/night-report-historical.jinja, scripts/install-base-packages.sh, src/js/hostbanner.js, src/js/modules/ws-service-client.js, start-daemon.sh
A small change to the routing, with some renaming for clarity and a new route that utilises the pod-facing URL for connecting with worker pods.
There are also a few fixes/cases of retyping for mypy.
=> DM-44568: Rewrite to use internal route for DDV worker pod-side websocket

python/lsst/ts/rubintv/config.py, python/lsst/ts/rubintv/handlers/handlers_helpers.py, python/lsst/ts/rubintv/main.py, tests/background/currentpoller_test.py
Includes a rebase of `tickets/DM-44913` as that branch (as yet unmerged but in for review) contains changes necessary for this patch.
=> DM-44663: Remove reliance on timeouts in testing

python/lsst/ts/rubintv/background/currentpoller.py, tests/handlers/api_test.py
I left my stethoscope in the patient...
=> DM-44979: Fix current polling only running for one cycle bug

python/lsst/ts/rubintv/models/models.py
See [https://docs.pydantic.dev/2.7/api/config/#pydantic.config.ConfigDict.arbitrary_types_allowed](https://docs.pydantic.dev/2.7/api/config/#pydantic.config.ConfigDict.arbitrary_types_allowed)
=> DM-45027: Update model config method for pydantic 3.0

python/lsst/ts/rubintv/middleware/x_forwarded.py, python/lsst/ts/rubintv/models/models.py
Re-pushed with `ts-pre-commit-config  0.9.12`
=> DM-45031: Run pending isort hook

python/lsst/ts/rubintv/background/historicaldata.py, src/sass/colours.sass
To fix a horrible bug where historical data was being stored incorrectly and lost to the display.
=> DM-46515: Fix historical data not stored properly

python/lsst/ts/rubintv/models/models_data.yaml, python/lsst/ts/rubintv/templates/camera_parts/calendar.jinja
Also, fix bug where calendar months display out of order.
=> DM-47654: Add AOS residual FWHM channel to AOS cameras

package-lock.json, package.json, python/lsst/ts/rubintv/handlers/websocket_notifiers.py, python/lsst/ts/rubintv/templates/_layout.jinja, src/js/components/TableApp.js, src/js/modules/utils.js, src/js/modules/ws-service-client.js
To relieve some of the strain of sending large strings of data frequently over web sockets, payloads are compressed/decompressed using gzip.
=> DM-47827: Compress websocket data on send/receive

python/lsst/ts/rubintv/background/currentpoller.py, python/lsst/ts/rubintv/models/models_data.yaml, src/js/components/Clock.js, src/js/components/TableApp.js, src/js/components/TableControls.js
Also bug fixes for:
Night report link not showing up
Faulty table controls logic
=> DM-47893: Add TAI time difference

python/lsst/ts/rubintv/background/currentpoller.py, src/js/components/NightReport.js, tests/background/currentpoller_test.py, tests/handlers/api_test.py, tests/mockdata.py
Also re-factored the CurrentPoller test suite in an attempt to make further tests easier to write.
=> DM-44622: Fix night report plots not being updated

python/lsst/ts/rubintv/main.py, src/images/close-cross.svg, src/js/components/Modal.js, src/js/components/TableApp.js, src/js/components/TableControls.js, src/js/components/TableFilter.js, src/js/components/TableView.js, src/js/modules/utils.js, src/sass/buttons.sass, src/sass/calendar.sass, src/sass/modal.sass, src/sass/style.sass
To use, click on a column title & enter the value to filter on.
Caveats:
The filter treats all the metadata values as strings.
It only checks for complete string equality.
It only filters on the metadata columns although the channel columns can be selected.
=> DM-49539: Add simple filtering for tables

src/js/components/MediaDisplay.js
Thanks for the catch Sebastian!
=> DM-50523: Fix careless logic error

src/images/sorting-indicator.svg, src/js/components/TableApp.js, src/js/components/TableControls.js, src/js/components/TableView.js, src/sass/style.sass
Use shift-click on a meta column name to sort by that column's values
=> DM-50536: Add sorting for tables

python/lsst/ts/rubintv/handlers/api.py, python/lsst/ts/rubintv/handlers/pages.py, python/lsst/ts/rubintv/models/models_data.yaml, src/js/components/Banner.js, src/sass/style.sass, tests/handlers/api_test.py, tests/handlers/external_test.py
Also provide redirects for permalinks.
=> DM-50802: Change slac to usdf for display and urls

python/lsst/ts/rubintv/config.py, src/js/components/RubinCalendar.js
I merged the last PR before applying the suggested corrections. They are added here.
=> Make suggested changes from PR#262

Dockerfile, scripts/build-flutter-app.sh
Use fvm to manage Flutter version control.
Both `rubintv_visualization` and `rubin_chart` use fvm configs.
=> SITCOM-2199: Use fvm to install Flutter
